# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['demo/cli_interface.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config', 'config'),
        ('models', 'models'),
        ('services', 'services'),
        ('controllers', 'controllers'),
        ('README.md', '.'),
    ],
    hiddenimports=[
        'sys',
        'pathlib',
        'threading',
        'subprocess',
        'importlib',
        'pkg_resources',
        'google',
        'google.generativeai',
        'torch',
        'torch.nn',
        'numpy',
        'transformers',
        'sklearn',
        'scipy',
        'matplotlib',
        'seaborn',
        'pandas',
        'requests',
        'beautifulsoup4',
        'lxml',
        'openpyxl',
        'xlrd',
        'xlwt',
        'xlsxwriter',
        'pydantic',
        'typing_extensions',
        'colorama',
        'tqdm',
        'click',
        'rich',
        'prompt_toolkit',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'seaborn',
        'plotly',
        'bokeh',
        'altair',
        'holoviews',
        'panel',
        'streamlit',
        'dash',
        'gradio',
        'flask',
        'django',
        'fastapi',
        'uvicorn',
        'gunicorn',
        'celery',
        'redis',
        'pymongo',
        'sqlalchemy',
        'psycopg2',
        'pymysql',
        'sqlite3',
        'pymssql',
        'cx_Oracle',
        'pyodbc',
        'pypyodbc',
        'mysqlclient',
        'mariadb',
        'pymssql',
        'pyodbc',
        'teradata',
        'ibm_db',
        'pyhdb',
        'pysap',
        'pymqi',
        'pymqi',
        'pyodbc',
        'teradata',
        'ibm_db',
        'pyhdb',
        'pysap',
        'pymqi',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='HRM-Gemini-AI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)